target_tags:
    - 人間椅子
    - MUCC
    - 鴉
    - 9mm Parabellum Bullet
    - UNLIMITS
    - THE YELLOW MONKEY
    - 戸川純
    - アーバンギャルド
    - FoZZtone
    - Jeepta
    - 女王蜂
    - クウチュウ戦
    - チャラン・ポ・ランタン
    - LACCO TOWER
    - 竹原ピストル
    - MERRY
    - 中田裕二
    - 歌姫楽団
    - EGO-WRAPPIN'
    - hide
    - 椎名林檎
    - タテタカコ
    - 大槻ケンヂ
    - ROLLY
    - THE BACK HORN
    - キノコホテル
    - フジファブリック
    - チリヌルヲワカ
    - Jin-Machine
    - BRAHMAN
    - 八十八ヶ所巡礼
    - バックドロップシンデレラ
    - BUCK-TICK
    - 真空ホロウ
    - 空創ワルツ
    - 小島麻由美
    - ミソッカス
    - 己龍
    - cali≠gari
    - Amelie
    - 中村中
    - ザ・キャプテンズ
    - Acid Black Cherry
    - つしまみれ
    - THE CHERRY COKE$
    - 吉井和哉
    - HAWAIIAN6
    - 浅草ジンタ
    - 友川カズキ
    - 筋肉少女帯
    - THE ALFEE
    - HERE
    - 奥村愛子
    - 勝手にしやがれ
    - heidi.
    - それでも尚、未来に媚びる
